
ALTER TABLE "users" ALTER COLUMN "user_id" DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN "user_id" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "trips" ALTER COLUMN "trip_id" DROP DEFAULT;
ALTER TABLE "trips" ALTER COLUMN "trip_id" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "itineraries" ALTER COLUMN "itinerary_id" DROP DEFAULT;
ALTER TABLE "itineraries" ALTER COLUMN "itinerary_id" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "visitations" ALTER COLUMN "visitation_id" DROP DEFAULT;
ALTER TABLE "visitations" ALTER COLUMN "visitation_id" ADD GENERATED ALWAYS AS IDENTITY;

ALTER TABLE "refresh_tokens" ALTER COLUMN "token_id" DROP DEFAULT;
ALTER TABLE "refresh_tokens" ALTER COLUMN "token_id" ADD GENERATED ALWAYS AS IDENTITY;